export const defaultInfo = {
  // 基础资料
  item_1: {
    itemNo: "item_1",
    itemType: "JUDGE",
    answer: "",
    tabName: "BASIC_INFO",
  },
  item_2: {
    itemNo: "item_2",
    itemType: "JUDGE",
    answer: "",
    tabName: "BASIC_INFO",
  },
  item_3: {
    itemNo: "item_3",
    itemType: "JUDGE",
    answer: "",
    tabName: "BASIC_INFO",
  },
  item_4: {
    itemNo: "item_4",
    itemType: "JUDGE",
    answer: "",
    tabName: "BASIC_INFO",
  },
  item_5: {
    itemNo: "item_5",
    itemType: "JUDGE",
    answer: "",
    tabName: "BASIC_INFO",
  },
  item_6: {
    itemNo: "item_6",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: "BASIC_INFO",
  },
  // 用工资料
  item_7: {
    itemNo: "item_7",
    itemType: "JUDGE",
    answer: "",
    tabName: "EMP_INFO",
  },
  item_8: {
    itemNo: "item_8",
    itemType: "JUDGE",
    answer: "",
    tabName: "EMP_INFO",
  },
  item_9: {
    itemNo: "item_9",
    itemType: "JUDGE",
    answer: "",
    tabName: "EMP_INFO",
  },
  item_10: {
    itemNo: "item_10",
    itemType: "JUDGE",
    answer: "",
    tabName: "EMP_INFO",
  },
  item_11: {
    itemNo: "item_11",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: "EMP_INFO",
  },
  // 实名制管理
  item_12: {
    itemNo: "item_12",
    itemType: "JUDGE",
    answer: "",
    tabName: "REL_MANAGE",
  },
  item_13: {
    itemNo: "item_13",
    itemType: "JUDGE",
    answer: "",
    tabName: "REL_MANAGE",
  },
  item_14: {
    itemNo: "item_14",
    itemType: "JUDGE",
    answer: "",
    tabName: "REL_MANAGE",
  },
  item_15: {
    itemNo: "item_15",
    itemType: "JUDGE",
    answer: "",
    tabName: "REL_MANAGE",
  },
  item_16: {
    itemNo: "item_16",
    itemType: "JUDGE",
    answer: "",
    tabName: "REL_MANAGE",
  },
  item_17: {
    itemNo: "item_17",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: "REL_MANAGE",
  },
  // 农民工工资专户
  item_18: {
    itemNo: "item_18",
    itemType: "JUDGE",
    answer: "",
    tabName: "SALARY_ACCOUNT",
  },
  item_19: {
    itemNo: "item_19",
    itemType: "JUDGE",
    answer: "",
    tabName: "SALARY_ACCOUNT",
  },
  item_20: {
    itemNo: "item_20",
    itemType: "JUDGE",
    answer: "",
    tabName: "SALARY_ACCOUNT",
  },
  item_21: {
    itemNo: "item_21",
    itemType: "JUDGE",
    answer: "",
    tabName: "SALARY_ACCOUNT",
  },
  item_22: {
    itemNo: "item_22",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: "SALARY_ACCOUNT",
  },
  // 维权公示
  item_23: {
    itemNo: "item_23",
    itemType: "JUDGE",
    answer: "",
    tabName: "PUBLICITY_ANNOUNCE",
  },
  item_24: {
    itemNo: "item_24",
    itemType: "JUDGE",
    answer: "",
    tabName: "PUBLICITY_ANNOUNCE",
  },
  item_25: {
    itemNo: "item_25",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: "PUBLICITY_ANNOUNCE",
  },
  // 民工一
  item_26: {
    itemNo: "item_26",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 1,
  },
  item_27: {
    itemNo: "item_27",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 1,
  },
  item_28: {
    itemNo: "item_28",
    itemType: "JUDGE",
    answer: "",
    tabName: 1,
  },
  item_29: {
    itemNo: "item_29",
    itemType: "JUDGE",
    answer: "",
    tabName: 1,
  },
  item_30: {
    itemNo: "item_30",
    itemType: "JUDGE",
    answer: "",
    tabName: 1,
  },
  item_31: {
    itemNo: "item_31",
    itemType: "JUDGE",
    answer: "",
    tabName: 1,
  },
  item_32: {
    itemNo: "item_32",
    itemType: "JUDGE",
    answer: "",
    tabName: 1,
  },
  item_33: {
    itemNo: "item_33",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: 1,
  },
  // 民工二
  item_34: {
    itemNo: "item_34",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 2,
  },
  item_35: {
    itemNo: "item_35",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 2,
  },
  item_36: {
    itemNo: "item_36",
    itemType: "JUDGE",
    answer: "",
    tabName: 2,
  },
  item_37: {
    itemNo: "item_37",
    itemType: "JUDGE",
    answer: "",
    tabName: 2,
  },
  item_38: {
    itemNo: "item_38",
    itemType: "JUDGE",
    answer: "",
    tabName: 2,
  },
  item_39: {
    itemNo: "item_39",
    itemType: "JUDGE",
    answer: "",
    tabName: 2,
  },
  item_40: {
    itemNo: "item_40",
    itemType: "JUDGE",
    answer: "",
    tabName: 2,
  },
  item_41: {
    itemNo: "item_41",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: 2,
  },
  // 民工三
  item_42: {
    itemNo: "item_42",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 3,
  },
  item_43: {
    itemNo: "item_43",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 3,
  },
  item_44: {
    itemNo: "item_44",
    itemType: "JUDGE",
    answer: "",
    tabName: 3,
  },
  item_45: {
    itemNo: "item_45",
    itemType: "JUDGE",
    answer: "",
    tabName: 3,
  },
  item_46: {
    itemNo: "item_46",
    itemType: "JUDGE",
    answer: "",
    tabName: 3,
  },
  item_47: {
    itemNo: "item_47",
    itemType: "JUDGE",
    answer: "",
    tabName: 3,
  },
  item_48: {
    itemNo: "item_48",
    itemType: "JUDGE",
    answer: "",
    tabName: 3,
  },
  item_49: {
    itemNo: "item_49",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: 3,
  },
  // 民工四
  item_50: {
    itemNo: "item_50",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 4,
  },
  item_51: {
    itemNo: "item_51",
    itemType: "TEXT_BOX",
    answer: "",
    tabName: 4,
  },
  item_52: {
    itemNo: "item_52",
    itemType: "JUDGE",
    answer: "",
    tabName: 4,
  },
  item_53: {
    itemNo: "item_53",
    itemType: "JUDGE",
    answer: "",
    tabName: 4,
  },
  item_54: {
    itemNo: "item_54",
    itemType: "JUDGE",
    answer: "",
    tabName: 4,
  },
  item_55: {
    itemNo: "item_55",
    itemType: "JUDGE",
    answer: "",
    tabName: 4,
  },
  item_56: {
    itemNo: "item_56",
    itemType: "JUDGE",
    answer: "",
    tabName: 4,
  },
  item_57: {
    itemNo: "item_57",
    itemType: "REMARK",
    answer: { files: [], remark: "" },
    tabName: 4,
  },
};

export const fillInfo = {
  item_1: { itemNo: "item_1", itemType: "JUDGE", answer: "1" },
  item_2: { itemNo: "item_2", itemType: "JUDGE", answer: "0" },
  item_3: { itemNo: "item_3", itemType: "JUDGE", answer: "1" },
  item_4: { itemNo: "item_4", itemType: "JUDGE", answer: "1" },
  item_5: { itemNo: "item_5", itemType: "JUDGE", answer: "0" },
  item_6: {
    itemNo: "item_6",
    itemType: "REMARK",
    answer: { files: [{ name: "bg.png", url: "https://axzo-public.oss-cn-chengdu.aliyuncs.com/bg.png" }], remark: "11111" },
  },
  item_7: { itemNo: "item_7", itemType: "JUDGE", answer: "0" },
  item_8: { itemNo: "item_8", itemType: "JUDGE", answer: "1" },
  item_9: { itemNo: "item_9", itemType: "JUDGE", answer: "1" },
  item_10: { itemNo: "item_10", itemType: "JUDGE", answer: "0" },
  item_11: {
    itemNo: "item_11",
    itemType: "REMARK",
    answer: {
      files: [
        {
          name: "d8620c1b234d470fb25ec4d8c2996594_tplv-k3u1fbpfcp-zoom-crop-mark_1304_1304_1304_734.webp",
          url: "https://axzo-public.oss-cn-chengdu.aliyuncs.com/d8620c1b234d470fb25ec4d8c2996594_tplv-k3u1fbpfcp-zoom-crop-mark_1304_1304_1304_734.webp",
        },
      ],
      remark: "5646546",
    },
  },
  item_12: { itemNo: "item_12", itemType: "JUDGE", answer: "0" },
  item_13: { itemNo: "item_13", itemType: "JUDGE", answer: "1" },
  item_14: { itemNo: "item_14", itemType: "JUDGE", answer: "1" },
  item_15: { itemNo: "item_15", itemType: "JUDGE", answer: "1" },
  item_16: { itemNo: "item_16", itemType: "JUDGE", answer: "0" },
  item_17: {
    itemNo: "item_17",
    itemType: "REMARK",
    answer: { files: [{ name: "favicon.ico", url: "https://axzo-public.oss-cn-chengdu.aliyuncs.com/favicon.ico" }], remark: "45654565" },
  },
  item_18: { itemNo: "item_18", itemType: "JUDGE", answer: "1" },
  item_19: { itemNo: "item_19", itemType: "JUDGE", answer: "1" },
  item_20: { itemNo: "item_20", itemType: "JUDGE", answer: "1" },
  item_21: { itemNo: "item_21", itemType: "JUDGE", answer: "0" },
  item_22: {
    itemNo: "item_22",
    itemType: "REMARK",
    answer: {
      files: [{ name: "tnd-map-orange.png", url: "https://axzo-public.oss-cn-chengdu.aliyuncs.com/tnd-map-orange.png" }],
      remark: "456546544554",
    },
  },
  item_23: { itemNo: "item_23", itemType: "JUDGE", answer: "1" },
  item_24: { itemNo: "item_24", itemType: "JUDGE", answer: "0" },
  item_25: {
    itemNo: "item_25",
    itemType: "REMARK",
    answer: { files: [{ name: "tnd-map-orange.png", url: "https://axzo-public.oss-cn-chengdu.aliyuncs.com/tnd-map-orange.png" }], remark: "554555" },
  },
  item_26: { itemNo: "item_26", itemType: "TEXT_BOX", answer: "1" },
  item_27: { itemNo: "item_27", itemType: "TEXT_BOX", answer: "11111111111" },
  item_28: { itemNo: "item_28", itemType: "JUDGE", answer: "1" },
  item_29: { itemNo: "item_29", itemType: "JUDGE", answer: "1" },
  item_30: { itemNo: "item_30", itemType: "JUDGE", answer: "1" },
  item_31: { itemNo: "item_31", itemType: "JUDGE", answer: "1" },
  item_32: { itemNo: "item_32", itemType: "JUDGE", answer: "0" },
  item_33: { itemNo: "item_33", itemType: "REMARK", answer: { files: [], remark: "111111111111111111111" } },
  item_34: { itemNo: "item_34", itemType: "TEXT_BOX", answer: "2" },
  item_35: { itemNo: "item_35", itemType: "TEXT_BOX", answer: "22222222222" },
  item_36: { itemNo: "item_36", itemType: "JUDGE", answer: "0" },
  item_37: { itemNo: "item_37", itemType: "JUDGE", answer: "0" },
  item_38: { itemNo: "item_38", itemType: "JUDGE", answer: "1" },
  item_39: { itemNo: "item_39", itemType: "JUDGE", answer: "1" },
  item_40: { itemNo: "item_40", itemType: "JUDGE", answer: "1" },
  item_41: { itemNo: "item_41", itemType: "REMARK", answer: { files: [], remark: "" } },
  item_42: { itemNo: "item_42", itemType: "TEXT_BOX", answer: "3" },
  item_43: { itemNo: "item_43", itemType: "TEXT_BOX", answer: "33333333333" },
  item_44: { itemNo: "item_44", itemType: "JUDGE", answer: "1" },
  item_45: { itemNo: "item_45", itemType: "JUDGE", answer: "1" },
  item_46: { itemNo: "item_46", itemType: "JUDGE", answer: "1" },
  item_47: { itemNo: "item_47", itemType: "JUDGE", answer: "1" },
  item_48: { itemNo: "item_48", itemType: "JUDGE", answer: "0" },
  item_49: { itemNo: "item_49", itemType: "REMARK", answer: { files: [], remark: "" } },
  item_50: { itemNo: "item_50", itemType: "TEXT_BOX", answer: "4" },
  item_51: { itemNo: "item_51", itemType: "TEXT_BOX", answer: "44444444444" },
  item_52: { itemNo: "item_52", itemType: "JUDGE", answer: "1" },
  item_53: { itemNo: "item_53", itemType: "JUDGE", answer: "1" },
  item_54: { itemNo: "item_54", itemType: "JUDGE", answer: "0" },
  item_55: { itemNo: "item_55", itemType: "JUDGE", answer: "0" },
  item_56: { itemNo: "item_56", itemType: "JUDGE", answer: "1" },
  item_57: {
    itemNo: "item_57",
    itemType: "REMARK",
    answer: { files: [{ name: "logo-cdht.png", url: "https://axzo-public.oss-cn-chengdu.aliyuncs.com/logo-cdht.png" }], remark: "434343" },
  },
};
